version: '3.1'
services:
  mongo:
    container_name: mongo-db
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    networks:
      - local-network

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8900:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_URL: mongodb://root:123456@mongo:27017/
    networks:
      - local-network

networks:
  local-network:
    driver: bridge