version: '3.9'
services:
  portainer:
    image: portainer/portainer-ce
    restart: always
    ports:
      - "$DOCKER_PORT_AGENT_COMMUNICATION:8000"
      - "$DOCKER_PORT_UI:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $VOLUME_DATA_PATH:/data