version: "lastest"
services:
  db:
    image: mysql
    container_name: mysql_db
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 123456@abcX
